import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div classname="container-fluid">
       <div className="row">
         <div className="col-lg-3 col-12" style={{border:"1px solid #aaaaaa"}}>
           heloo
         </div>
         <div className="col-9 row" style={{border:"1px solid #aaaaaa"}}>
           <div className="col-12 col-lg-4">
           a
           </div>
             <div className="col-12 col-lg-4">
                 a
             </div>
             <div className="col-12 col-lg-4">
                 a
             </div>
         </div>
       </div>
     </div>
    </>
  )
}
